version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.Dockerfile
    volumes:
      - ./app:/var/www
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

  app:
    build:
      context: .
      dockerfile: ./dockerfiles/php.Dockerfile
    volumes:
      - ./app:/var/www
    container_name: app

  db:
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: Booklibrary
      MYSQL_ROOT_PASSWORD: secret_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    container_name: db

volumes:
  dbdata: